title: The Devil's Advocate
email: your@email.com
description: Stirring the pot, one story at a time.
baseurl: ""
url: "https://thedevilsadvocate-us.github.io"

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 9
paginate_path: "/page/:num/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "The Devil's Advocate"